---
galaxy_info:
  author: Larry Smith Jr.
  description: Installs and configures OpenLDAP and phpLDAPadmin
  license: MIT
  min_ansible_version: 2.8

  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - trusty
        - xenial
  # - name: Fedora
  #   versions:
  #   - all
  #   - 25
  # - name: SomePlatform
  #   versions:
  #   - all
  #   - 1.0
  #   - 7
  #   - 99.99

  galaxy_tags:
    - administration
    - ldap
    - authentication

dependencies: []
