---
- name: Configura nó de controle do Ansible
  gather_facts: false
  hosts:
    - ansible
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - vars/hosts.yaml
  roles:
    - no-ipv6
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      loop: '{{ linux_hosts_file }}'

    - name: Ajustando /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: 127.0.1.1 ansible
        state: absent

    - name: Adiciona usuário suporte
      ansible.builtin.user:
        name: suporte
        state: present
        shell: /bin/bash
        password: '$1$gGnGcYuu$nfGgkuOm8xRp9vvL8rmIM/'

    - name: Garantir permissão de root para o usuário suporte
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        insertafter: 'vagrant ALL=(ALL) NOPASSWD: ALL'
        line: 'suporte ALL=(ALL) NOPASSWD: ALL'

    - name: Configurando os subdiretórios para o Ansible
      ansible.builtin.file:
        path: '{{ item }}'
        state: directory
        mode: '0700'
        owner: suporte
        group: suporte
      loop:
        - /home/suporte/.ansible/cache/facts
        - /home/suporte/.ansible/logs
        - /home/suporte/.ansible/tmp
        - /home/suporte/.ssh

    - name: Criando diretório lookup
      ansible.posix.synchronize:
        src: files/lookup
        dest: /home/suporte

    - name: Criando diretório modulos
      ansible.posix.synchronize:
        src: files/modulos
        dest: /home/suporte

    - name: Criando diretório molecule
      ansible.posix.synchronize:
        src: files/molecule
        dest: /home/suporte

    - name: Criando diretório playbooks
      ansible.posix.synchronize:
        src: files/playbooks
        dest: /home/suporte

    - name: Criando diretório roles
      ansible.posix.synchronize:
        src: files/roles
        dest: /home/suporte

    - name: Criando diretório site
      ansible.posix.synchronize:
        src: files/site
        dest: /home/suporte

    - name: Criando diretório awx
      ansible.posix.synchronize:
        src: files/awx
        dest: /home/suporte