---
- hosts:
    - ansible
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - vars/hosts.yaml
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items: '{{ linux_hosts_file }}'

    - name: Ajustando /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: 127.0.1.1 ansible
        state: absent

    - name: 'Criando diretório docker-nfs-server-rocky'
      ansible.posix.synchronize:
        src: files/docker-nfs-server-rocky
        dest: /home/suporte

    - name: Criando diretório docker-nfs-server-ubuntu
      ansible.posix.synchronize:
        src: files/docker-nfs-server-ubuntu
        dest: /home/suporte

    - name: Criando diretório lookup
      ansible.posix.synchronize:
        src: files/lookup
        dest: /home/suporte

    - name: Criando diretório modulos
      ansible.posix.synchronize:
        src: files/modulos
        dest: /home/suporte

    - name: Criando diretório molecule
      ansible.posix.synchronize:
        src: files/molecule
        dest: /home/suporte

    - name: Criando diretório playbooks
      ansible.posix.synchronize:
        src: files/playbooks
        dest: /home/suporte

    - name: Criando diretório roles
      ansible.posix.synchronize:
        src: files/roles
        dest: /home/suporte

    - name: Criando diretório site
      ansible.posix.synchronize:
        src: files/site
        dest: /home/suporte

    - name: Criando diretório awx
      ansible.posix.synchronize:
        src: files/awx
        dest: /home/suporte

    - name: Reinicia o SSH
      service:
        name: sshd
        daemon_reload: yes
        state: restarted
