---
- hosts:
    - balancer
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: false
  vars_files:
    - vars/hosts.yaml
  roles:
    - no-ipv6
  tasks:
    - name: Garantindo /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      loop: '{{ linux_hosts_file }}'

    - name: Ajustando /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: 127.0.1.1 balancer balancer
        state: absent

    - name: Adiciona usuário suporte
      ansible.builtin.user:
        name: suporte
        state: present
        shell: /bin/bash
        password: '$1$gGnGcYuu$nfGgkuOm8xRp9vvL8rmIM/'

    - name: Configurando o OpenSSH do usuário suporte
      ansible.builtin.file:
        path: /home/suporte/.ssh
        state: directory
        mode: '0700'
        owner: suporte
        group: suporte

    - name: Garantir permissão de root para o usuário suporte
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        insertafter: 'vagrant ALL=(ALL) NOPASSWD: ALL'
        line: 'suporte ALL=(ALL) NOPASSWD: ALL'

    - name: Libera HTTP no firewall
      ansible.builtin.command:
        cmd: firewall-cmd --permanent --add-service=http

    - name: Desabilita o DHCPv6 no firewall
      ansible.builtin.command:
        cmd: firewall-cmd --permanent --remove-service=dhcpv6-client
      notify:
        - 'Reload firewall rules'

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /etc/sysctl.d/
        state: directory
        mode: '0755'

  handlers:
    - name: 'Reload firewall rules'
      ansible.builtin.command:
        cmd: firewall-cmd --reload