---
- hosts: dbserver
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: false
  vars_files:
    - vars/hosts.yaml
  roles:
    - no-ipv6
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      loop: '{{ linux_hosts_file }}'

    - name: Adiciona o usuário suporte
      ansible.builtin.import_tasks:
        file: common_user.yaml

    - name: Ajustando /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: 127.0.1.1 dbserver
        state: absent