---
- hosts: webserver2
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - vars/hosts.yaml
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items: '{{ linux_hosts_file }}'

    - name: Ajustando /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: 127.0.1.1 webserver2
        state: absent

    - name: Substitui 'mirrorlist' por '#mirrorlist' nos arquivos de configuração do repo
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: '^mirrorlist='
        replace: '#mirrorlist='
      with_fileglob:
        - /etc/yum.repos.d/CentOS-*

    - name: Muda a URL base de 'mirror.centos.org' para 'vault.centos.org'
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: '#baseurl=http://mirror.centos.org'
        replace: 'baseurl=http://vault.centos.org'
      with_fileglob:
        - /etc/yum.repos.d/CentOS-*

    - name: Limpa todos os caches do DNF
      ansible.builtin.command:
        cmd: dnf clean all

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /etc/sysctl.d/
        state: directory
        mode: '0755'

    - name: Desabilita o DHCPv6 no firewall
      ansible.builtin.command:
        cmd: firewall-cmd --permanent --remove-service=dhcpv6-client
      notify:
        - 'Reload firewall rules'

    - name: Desabilita o uso de IPv6 no host
      lineinfile:
        path: /etc/sysctl.d/60-disable-ipv6.conf
        line: '{{ item }}'
        state: present
        create: true
      with_items:
        - net.ipv6.conf.all.disable_ipv6 = 1
        - net.ipv6.conf.default.disable_ipv6 = 1
        - net.ipv6.conf.lo.disable_ipv6 = 1
      notify:
        - 'Reload sysctl'
  handlers:
    - name: 'Reload firewall rules'
      ansible.builtin.command:
        cmd: firewall-cmd --reload
    - name: 'Reload sysctl'
      ansible.builtin.command:
        cmd: sysctl -p /etc/sysctl.d/60-disable-ipv6.conf