---
- hosts: webserver2
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: false
  vars_files:
    - vars/hosts.yaml
  roles:
    - no-ipv6
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      loop: '{{ linux_hosts_file }}'

    - name: Ajustando /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: 127.0.1.1 webserver2
        state: absent

    - name: Adiciona o usuário suporte
      ansible.builtin.import_tasks:
        file: common_user.yaml

    - name: Libera HTTP no firewall
      ansible.builtin.command:
        cmd: firewall-cmd --permanent --add-service=http

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /etc/sysctl.d/
        state: directory
        mode: '0755'

    - name: Desabilita o DHCPv6 no firewall
      ansible.builtin.command:
        cmd: firewall-cmd --permanent --remove-service=dhcpv6-client
      notify:
        - 'Reload firewall rules'

  handlers:
    - name: 'Reload firewall rules'
      ansible.builtin.command:
        cmd: firewall-cmd --reload