---
- name: Configuração básica do webserver1
  hosts: webserver1
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - vars/hosts.yaml
  roles:
    - no-ipv6
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items: '{{ linux_hosts_file }}'

    - name: Adiciona usuário suporte
      ansible.builtin.user:
        name: suporte
        state: present
        shell: /bin/bash
        password: '$1$gGnGcYuu$nfGgkuOm8xRp9vvL8rmIM/'

    - name: Garantir permissão de root para o usuário suporte
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        insertafter: 'vagrant ALL=(ALL) NOPASSWD: ALL'
        line: 'suporte ALL=(ALL) NOPASSWD: ALL'

    - name: Configurando o OpenSSH do usuário suporte
      ansible.builtin.file:
        path: /home/suporte/.ssh
        state: directory
        mode: '0700'
        owner: suporte
        group: suporte

    - name: Ajustando /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: 127.0.1.1 webserver1
        state: absent
  handlers:
    - name: 'Reload firewall rules'
      ansible.builtin.command:
        cmd: firewall-cmd --reload