---
- hosts: webserver1
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - vars/hosts.yaml
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items: '{{ linux_hosts_file }}'

    - name: Ajustando /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: 127.0.1.1 webserver1
        state: absent
