---
- hosts: webserver2
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - vars/hosts.yaml
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items: '{{ linux_hosts_file }}'

    - name: Ajustando /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: 127.0.1.1 webserver2
        state: absent

    - name: Adiciona usuário suporte
      ansible.builtin.user:
        name: suporte
        state: present
        shell: /bin/bash
        password: '$1$gGnGcYuu$nfGgkuOm8xRp9vvL8rmIM/'

    - name: Garantir permissão de root para o usuário suporte
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        insertafter: 'vagrant ALL=(ALL) NOPASSWD: ALL'
        line: 'suporte ALL=(ALL) NOPASSWD: ALL'

    - name: Configurando o OpenSSH do usuário suporte
      ansible.builtin.file:
        path: /home/suporte/.ssh
        state: directory
        mode: '0700'
        owner: suporte
        group: suporte

    - name: Libera HTTP no firewall
      ansible.builtin.command:
        cmd: firewall-cmd --permanent --add-service=http

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /etc/sysctl.d/
        state: directory
        mode: '0755'

    - name: Desabilita o DHCPv6 no firewall
      ansible.builtin.command:
        cmd: firewall-cmd --permanent --remove-service=dhcpv6-client
      notify:
        - 'Reload firewall rules'

    - name: Desabilita o uso de IPv6 no host
      lineinfile:
        path: /etc/sysctl.d/60-disable-ipv6.conf
        line: '{{ item }}'
        state: present
        create: true
      with_items:
        - net.ipv6.conf.all.disable_ipv6 = 1
        - net.ipv6.conf.default.disable_ipv6 = 1
        - net.ipv6.conf.lo.disable_ipv6 = 1
      notify:
        - 'Reload sysctl'
  handlers:
    - name: 'Reload firewall rules'
      ansible.builtin.command:
        cmd: firewall-cmd --reload
    - name: 'Reload sysctl'
      ansible.builtin.command:
        cmd: sysctl -p /etc/sysctl.d/60-disable-ipv6.conf