---
- name: Configuração básica do webserver1
  hosts: webserver1
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - vars/hosts.yaml
  roles:
    - no-ipv6
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      loop: '{{ linux_hosts_file }}'

    - name: Adiciona o usuário suporte
      ansible.builtin.import_tasks:
        file: common_user.yaml

    - name: Ajustando /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: 127.0.1.1 webserver1
        state: absent
  handlers:
    - name: 'Reload firewall rules'
      ansible.builtin.command:
        cmd: firewall-cmd --reload