---
- name: Instala servidor Nginx no Debian/Ubuntu
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true
  notify:
    - Start Nginx Ubuntu
  tags: balancer

- name: Instala servidor Nginx no RedHat/CentOS
  when: ansible_os_family == "RedHat"
  ansible.builtin.yum:
    name: nginx
    state: present
  notify:
    - Start Nginx CentOS
  tags: balancer

- name: Inicia e ativa na inicializacao o servico nginx
  when: ansible_os_family == "RedHat"
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
  tags: balancer
