---
- name: Start MySQL-Debian
  ansible.builtin.systemd:
    name: mariadb
    state: started
- name: Start MySQL-RedHat
  ansible.builtin.systemd:
    name: mariadb-server
    state: started
- name: Restart MySQL-Debian
  ansible.builtin.systemd:
    name: mariadb
    state: restarted
- name: Start MySQL-RedHat
  ansible.builtin.systemd:
    name: mariadb-server
    state: restarted
    enable: true
