---
- name: Start Nginx Ubuntu
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Start Nginx Rocky Linux
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Restart Nginx Ubuntu
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Restart Nginx Rocky Linux
  ansible.builtin.service:
    name: nginx
    state: restarted
