---
- name: Verifica o funcionamento do servidor MySQL
  hosts: all
  gather_facts: false
  tasks:
  - name: Example assertion
    assert:
      that: true
  - name: Testando se a tabela foi importada no MySQL
    shell: "mysql -u root -p4linux -e 'USE dexter500; SHOW TABLES;' | grep funcionarios"
    register: mysql_result
    failed_when: mysql_result.stdout != "funcionarios"
