---
galaxy_info:
  role_name: conf_base
  author: sua_conta_github
  description: Configuracao Base de usuários, pacotes e hosts
  company: 4Linux
  license: GPLv3
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
    - name: EL
      versions:
        - 8
  galaxy_tags:
    -  users
    -  packages
    -  hosts
dependencies: []
