---
galaxy_info:
  role_name: apache
  author: 4Linux DevOps
  description: Instalação e Configuração do servidor Apache com Molecule
  company: 4Linux
  license: GPLv3
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
    - name: EL
      versions:
        - 8
  galaxy_tags:
    - apache
dependencies: []
