---
packages_debian:
  - tzdata
  - dnsutils
  - bash-completion
  - unzip
  - bzip2
  - htop
  - vim
  - mlocate
  - nfs-common
packages_redhat:
  - tzdata
  - bind-utils
  - unzip
  - bzip2
  - vim-enhanced
  - mlocate
  - htop
  - nfs-utils
