---
- name: Ler o arquivo /etc/hosts
  ansible.builtin.command:
    cmd: cat /etc/hosts
  register: content
  changed_when: false
  tags: hosts

- name: Limpa o arquivo /etc/hosts
  ansible.builtin.shell: echo '' > /etc/hosts
  when: "'172.16.0.199 ansible.4labs ansible' not in content.stdout"
  changed_when: false
  tags: hosts

- name: Configuracao do arquivo /etc/hosts
  when: "'172.16.0.199 ansible.4labs ansible' not in content.stdout"
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }} {{ item.fqdn }} {{ item.alias }}"
  with_items:
    - {ip: '127.0.0.1', fqdn: 'localhost.localdomain', alias: 'localhost'}
    - {ip: '172.16.0.199', fqdn: 'ansible.4labs', alias: 'ansible'}
    - {ip: '172.16.0.200', fqdn: 'balancer.4labs', alias: 'balancer'}
    - {ip: '172.16.0.201', fqdn: 'webserver1.4labs', alias: 'webserver1'}
    - {ip: '172.16.0.202', fqdn: 'webserver2.4labs', alias: 'webserver2'}
    - {ip: '172.16.0.203', fqdn: 'dbserver.4labs', alias: 'dbserver'}
    - {ip: '172.16.0.204', fqdn: 'winclient.4labs', alias: 'winclient'}
  tags: hosts
