---
- name: Instala pacotes base no Debian/Ubuntu
  when: ansible_os_family == "Debian"
  apt:
    name: "{{ packages_debian }}"
    state: present
    update_cache: true
  tags: packages

- name: Instala pacotes base no RedHat/CentOS
  when: ansible_os_family == "RedHat"
  yum:
    name: "{{ packages_redhat }}"
    state: present
  tags: packages
