---
- name: Start NFS Ubuntu
  ansible.builtin.service:
    name: nfs-kernel-server
    state: started

- name: Start NFS CentOS
  ansible.builtin.service:
    name: nfs-server
    state: started

- name: Restart NFS Ubuntu
  ansible.builtin.service:
    name: nfs-kernel-server
    state: restarted

- name: Restart NFS CentOS
  ansible.builtin.service:
    name: nfs-server
    state: restarted
