---
- name: Define configuracao do servidor MySQL no Debian/Ubuntu
  when: ansible_os_family == "Debian"
  ansible.builtin.template:
    src: mysql-debian.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart MySQL-Debian
  tags: banco

- name: Define configuracao do servidor MySQL no RedHat/CentOS
  when: ansible_os_family == "RedHat"
  ansible.builtin.template:
    src: mysql-redhat.cnf.j2
    dest: /etc/my.cnf.d/server.cnf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart MySQL-RedHat
  tags: banco

- name: Define o arquivo .my.cnf
  ansible.builtin.copy:
    src: root_pass.cnf
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: "0600"
  tags: banco

- name: Define o arquivo dump.sql
  ansible.builtin.copy:
    src: dump.sql
    dest: /tmp
    owner: root
    group: root
    mode: "0644"
  tags: banco
