---
- name: Inclui variaveis para distribuicoes Linux
  include_vars: "{{ ansible_os_family }}.yml"
  tags: banco

- name: Instala pacotes para servidor MySQL no Debian/Ubuntu
  when: ansible_os_family == "Debian"
  apt:
    name: "{{ packages_debian }}"
    state: present
    update_cache: true
  notify:
    - Start MySQL-Debian
  tags: banco

- name: Instala pacotes para servidor MySQL no RedHat/CentOS
  when: ansible_os_family == "RedHat"
  dnf:
    name: "{{ packages_redhat }}"
    state: present
  notify:
    - Start MySQL-RedHat
  tags: banco
