---
- name: Define instalacao do servidor MySQL
  ansible.builtin.import_tasks: install.yml

- name: Define configuracao do servidor MySQL
  ansible.builtin.import_tasks: configure.yml

- name: Adiciona, banco e tabelas no MySQL
  ansible.builtin.import_tasks: database.yml
