---
- name: Converge
  hosts: all
  vars:
    etc_hosts_add_all_hosts: true
  tasks:
    # - name: Include ansible-etc-hosts
    #   include_role:
    #     name: ansible-etc-hosts
    - name: Include ansible-openldap
      include_role:
        name: ansible-openldap
