---
- name: Inicia o serviço rpcbind
  ansible.builtin.service:
    name: rpcbind
    state: started

- name: Define o arquivo de configuracao do servidor NFS no Debian/Ubuntu
  when: ansible_os_family == "Debian"
  ansible.builtin.copy:
    src: exports
    dest: /etc/exports
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart NFS Ubuntu
  tags: nfs

- name: Define o arquivo de configuracao do servidor NFS no RedHat/CentOS
  when: ansible_os_family == "RedHat"
  ansible.builtin.copy:
    src: exports
    dest: /etc/exports
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart NFS CentOS
  tags: nfs

- name: Verifica se diretorio /opt/site/admin existe
  ansible.builtin.stat:
    path: /opt/site/admin
  register: site_directory

- name: Criando diretorio site
  when: not site_directory.stat.exists
  ansible.builtin.copy:
    src: site/
    dest: /opt/site
    owner: root
    group: root
    mode: "0755"
  tags: nfs
