---
- name: Limpa o arquivo /etc/hosts
  shell: echo '' > /etc/hosts
  tags: hosts

- name: Configuracao do arquivo /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }} {{ item.fqdn }} {{ item.alias }}"
  with_items:
    - { ip: '127.0.0.1', fqdn: 'localhost.localdomain', alias: 'localhost' }
    - { ip: '172.16.0.199', fqdn: 'ansible-server.4labs.example', alias: 'ansible-server' }
    - { ip: '172.16.0.200', fqdn: 'balancer.4labs.example', alias: 'balancer' }
    - { ip: '172.16.0.201', fqdn: 'webserver1.4labs.example', alias: 'webserver1' }
    - { ip: '172.16.0.202', fqdn: 'webserver2.4labs.example', alias: 'webserver2' }
    - { ip: '172.16.0.203', fqdn: 'dbserver.4labs.example', alias: 'dbserver' }
  tags: hosts
