---
- hosts: webservers
  pre_tasks:
  - name: Instala cliente NFS em distribuições baseadas no Debian
    ansible.builtin.apt:
      name: nfs-common
      state: present
      update_cache: true
    when: ansible_os_family == "Debian"
  - name: Instala cliente NFS em distribuições baseadas no RedHat
    ansible.builtin.dnf:
      name: nfs-utils
    when: ansible_os_family == "RedHat"
  roles:
    - web_server
