---
- name: Start Apache
  service:
    name: apache2
    state: started

- name: Start Httpd
  service:
    name: httpd
    state: started

- name: Restart Apache
  service:
    name: apache2
    state: restarted

- name: Restart Httpd
  service:
    name: httpd
    state: restarted
