---
- name: Verifica o funcionamento do servidor Web Apache
  hosts: all
  gather_facts: false
  vars:
    - expected_content: "Pagina de teste do Apache"
  tasks:
    - name: Example assertion
      ansible.builtin.assert:
        that: true
    - name: Testando o acesso ao servidor Apache
      ansible.builtin.uri:
        url: http://localhost
        return_content: true
      register: site
      failed_when: "expected_content not in site.content"
