---
galaxy_info:
  role_name: nfs_server
  author: 4Linux DevOps
  description: Instalacao e Configuracao do servidor NFS
  company: 4Linux
  license: GPLv3
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
    - name: EL
      versions:
        - 8
  galaxy_tags:
    - nfs
dependencies:
  - conf-base        
