---
- hosts: local
  tasks:
    - name: Adiciona usuário helpdesk
      ansible.builtin.user:
        name: helpdesk
        state: present
        shell: /bin/bash
        password: $1$i5CwO/2J$JIaH55NqG10CDpYLqLAZf/
