---
- hosts: local
  vars:
    usuario: linus
  tasks:
    - name: Adiciona usuário
      ansible.builtin.user:
        name: "{{ usuario }}"
        state: present
        shell: /bin/bash
        password: $1$i5CwO/2J$JIaH55NqG10CDpYLqLAZf/
