---
- hosts: local
  vars_files:
    - /home/suporte/playbooks/vars.yml
  tasks:
    - name: Instala pacotes através de variáveis
      apt:
        name: {{ pacotes }}
        state: present
        update_cache: true
