---
- hosts: webservers
  tasks:
    - name: Instala o Apache no Debian/Ubuntu
      when: ansible_os_family == "Debian"
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: true
      register: apache2_installed
    - name: Instala o Apache no CentOS
      when: ansible_os_family == "RedHat"
      ansible.builtin.yum:
        name: httpd
        state: present
      register: httpd_installed
