---
galaxy_info:
  author: 4Linux DevOps
  description: Configuracao Base de usuarios, pacotes e hosts
  company: 4Linux
  license: GPLv3
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
    - name: EL
      versions:
        - 8
  galaxy_tags:
    -  users
    -  packages
    -  hosts
dependencies: []
